#!/usr/bin/env python3
"""Generate exact CSS unicode-range descriptors from the shipped WOFF2 faces.

Requirements:
    pip install fonttools brotli
"""

from pathlib import Path
import sys

try:
    from fontTools.ttLib import TTFont
except ImportError:
    sys.exit("fonttools not installed - run: pip install fonttools brotli")


ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
OUTPUT = ROOT / "src" / "bundled-unicode-ranges.ts"


def unicode_code_points(path: Path) -> list[int]:
    font = TTFont(path, lazy=True)
    glyphs = set()
    for table in font["cmap"].tables:
        if not table.isUnicode():
            continue
        for code_point, glyph_name in table.cmap.items():
            if glyph_name != ".notdef":
                glyphs.add(code_point)
    font.close()
    return sorted(glyphs)


def css_unicode_range(code_points: list[int]) -> str:
    ranges = []
    start = previous = code_points[0]
    for code_point in code_points[1:]:
        if code_point == previous + 1:
            previous = code_point
            continue
        ranges.append((start, previous))
        start = previous = code_point
    ranges.append((start, previous))
    return ", ".join(
        f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}" for start, end in ranges
    )


def main() -> None:
    entries = []
    for path in sorted(ASSETS.glob("*.woff2")):
        code_points = unicode_code_points(path)
        if not code_points:
            raise RuntimeError(f"{path.name} has no Unicode cmap coverage")
        entries.append((path.name, css_unicode_range(code_points)))

    lines = [
        "/** Generated by scripts/generate-bundled-unicode-ranges.py. */",
        "export const BUNDLED_FACE_UNICODE_RANGES: Readonly<Record<string, string>> = Object.freeze({",
    ]
    for filename, coverage in entries:
        lines.append(f"  {filename!r}:")
        lines.append(f"    {coverage!r},")
    lines.extend(["});", ""])
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
